const projects = [
    {
        name: "stylish",
        stack: ['Javascript','HTML', 'CSS'],
        type: 'Web',
        visibleKeywords:['frontend'],
        url: 'https://github.com/AnnaFinnerty/stylish',
        githubUrl: 'https://annafinnerty.github.io/stylish/',
        src: ['./img/Stylish1.png'],
        description: 'Interactive logo prototype for hair salon',
        caseStudy: [],
        live: true,
    },
    {
        name: "habit",
        stack: ['Express.js','Mongoose', 'MongoDB'],
        type: 'App',
        visibleKeywords:['frontend','backend'],
        url: 'https://dashboard.heroku.com/apps/ga-habit-app1',
        githubUrl: '',
        src: ['./img/Habit1.png'],
        description: 'Habit tracker app with RESTful routes',
        caseStudy: [],
        live: true,
    },
    {
        name: "citadels",
        stack: ['React.js','JSX', 'CSS', 'AI'],
        type: 'Game',
        visibleKeywords:['frontend','backend'],
        url: 'https://annafinnerty.github.io/Citadels/',
        githubUrl: '',
        src: ['./img/Citadels1.png'],
        description: 'React game with AI opponent',
        caseStudy: [],
        live: true,
    },
    {
        name: "Word Wrap",
        stack: ['Javascript','HTML', 'CSS'],
        type: 'Game',
        visibleKeywords:['frontend','backend'],
        url: 'https://annafinnerty.github.io/Citadels/',
        githubUrl: '',
        src: '',
        description: 'Animated JS game using prototype pattern',
        caseStudy: [],
        live: false,
    },
    {
        name: "named colorwheel",
        stack: ['React.js','JSX', 'CSS', 'AI'],
        type: 'Game',
        visibleKeywords:['frontend','backend'],
        url: 'https://annafinnerty.github.io/named_colorwheel/',
        githubUrl: 'https://annafinnerty.github.io/named_colorwheel/',
        src: ['./img/ColorWheel1.png'],
        description: 'React game with AI opponent',
        caseStudy: [],
        live: true,
    },    
    {
        name: "library",
        stack: ['Express.js','Mongoose', 'MongoDB'],
        type: 'App',
        visibleKeywords:['frontend','backend'],
        url: '',
        githubUrl: '',
        src: ['./img/Habit1.png'],
        description: 'books read/to read app in Express.js',
        caseStudy: [],
        live: true,
    },
    {
        name: "maura",
        stack: ['Java','jdbc', 'Jackson'],
        type: 'Java Program',
        visibleKeywords:['backend'],
        url: '',
        githubUrl: '',
        src: [''],
        description: 'Interface to algorhytymic match generator between missing persons and unidentified remains',
        caseStudy: [],
        live: false,
    }
]